language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install sphinx
  - pip install -r requirements.txt
script:
  - ./run.sh pytest
  - cd docs && make doc

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: docs/build/html/